# Utilise l'image de base nginx
FROM nginx:latest

# Copie le fichier HTML dans le répertoire de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Expose le port 80 pour accéder à l'application
EXPOSE 80

