name: Workflow1

on:
    push:
        branches:
            - main

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps: 
            - name: log hello world
              run: echo "Hello, world!"
            
            - name: git clone 
              uses: actions/checkout@v2

            - name: list files
              run: ls -l
    
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        steps: 
            - name: log hello world
              run: echo "Hello, world!"

            - name: list files
              run: ls -l

    
    job-3:
        runs-on: ubuntu-latest
        steps: 
            - name: make directory
              run: mkdir session5

            - name: list files
              run: ls -l        